image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.9

environment:
  GITHUB_TOKEN:
    secure: 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

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name redirect_port --icon icon_1.png --product-name redirect_port --product-version "1.0.13" --copyright "Copyright (c) 2023 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a redirect_port-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: redirect_port-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf redirect_port-macos.tar.gz -C dist redirect_port.app

  artifacts:
  - path: redirect_port-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf redirect_port-linux.tar.gz -C dist redirect_port

  artifacts:
  - path: redirect_port-linux.tar.gz

